drop table users IF EXISTS CASCADE;
drop type booking_status IF EXISTS CASCADE;
drop table items IF EXISTS CASCADE;
drop table booking IF EXISTS CASCADE;
drop table comments IF EXISTS CASCADE;

 create type booking_status as ENUM (
  'WAITING',
   'APPROVED',
    'REJECTED',
     'CANCELED');

create TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);
create TABLE IF NOT EXISTS items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  user_owner INTEGER REFERENCES users (id),
  description VARCHAR(1024) NOT NULL,
  available BOOLEAN NOT NULL,
  request INTEGER,
  CONSTRAINT pk_item PRIMARY KEY (id)
  );

   CREATE TABLE IF NOT EXISTS booking (
   id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   start_time TIMESTAMP NOT NULL,
   end_time TIMESTAMP NOT NULL,
   item_id INTEGER NOT NULL REFERENCES items (id) ,
   booker_id INTEGER NOT NULL REFERENCES users (id) ,
   status booking_status NOT NULL,
   CONSTRAINT pk_booking PRIMARY KEY (id)
   );



  CREATE TABLE IF NOT EXISTS comments (
   id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   text VARCHAR (1024) NOT NULL,
   author_id INTEGER NOT NULL REFERENCES users (id),
   item_id INTEGER NOT NULL REFERENCES items (id),
   created TIMESTAMP NOT NULL,
   CONSTRAINT pk_comments PRIMARY KEY (id)
   );


